preferWorkspacePackages: true
packages:
  #.npmrc文件 一般教程都是这样配置的：shamefully-hoist=true，
  # 但本人不推荐。这样做会把里面的依赖提升到全局node_module里面，有可能出现幽灵依赖的风险。

  # 存放公共的ui组件和util组件
  - 'packages/*'
  # 存放plugin插件
  - 'plugin/*'
  # 项目目录
  - 'apps/*'
  # 排除目录
  - '!**/test/*'
minimumReleaseAgeExclude:
  - '@types/vscode@1.134.0'
  - sass@1.103.0
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  esbuild: true
  bufferutil: true
  utf-8-validate: true
  core-js: false
  core-js-pure: false
  cssnano: false
  cwebp-bin: false
  es5-ext: false
  ghooks: false
  gifsicle: false
  jpegtran-bin: false
  mozjpeg: false
  optipng-bin: false
  pngquant-bin: false
  react-native-unimodules: false
  svelte-preprocess: false
  taro-hooks: false
  tsparticles-engine: false
  vue-demi: false
  vue-echarts: false
  yorkie: false
