version: '3.8'
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8090:8090'
    volumes:
      - '/promotion-web/node_modules'
      - './:/promotion-web'
