name: assemble taro mall h5

on:
  push:
    paths:
      - 'taotao-cloud-taro-mall/**'
    branches: [ master ]
    #tags: [ v* ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

defaults:
  run:
    working-directory: taotao-cloud-taro-mall

jobs:
  assemble:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'taotao-cloud-mall') }}
    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: use node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: cache node_modules folder
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules
          restore-keys: ${{ runner.os }}-node_modules

      - name: get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: cache yarn
        uses: actions/cache@v3
        env:
          cache-name: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn install and build
        run: |
          yarn
          yarn build:h5

      - name: deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "taotao-cloud-taro-mall/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_MALL_TARGET }}
